# Generated by Django 5.0.2 on 2024-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('user_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_name')),
                ('user_email', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='user_email')),
            ],
        ),
    ]
