# Generated by Django 5.0.4 on 2024-06-15 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('notification_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='notification_id')),
                ('notification_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='notification_content')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('playlist_id', models.CharField(blank=True, default='', max_length=30, null=True, unique=True, verbose_name='playlist_id')),
                ('playlist_title', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_name')),
                ('playlist_image', models.ImageField(blank=True, null=True, upload_to='playlist_images/', verbose_name='playlist_image')),
                ('public', models.BooleanField(default=True, verbose_name='public')),
                ('playlist_played_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_played_times')),
                ('playlist_loved_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_loved_number')),
                ('playlist_comment_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_comment_number')),
                ('playlist_saved_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_saved_number')),
                ('playlist_detail', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='playlist_detail')),
                ('playlist_attributes', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='playlist_attributes')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('playlist_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_id')),
                ('comment_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='comment_id')),
                ('comment_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='comment_content')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Loved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('playlist_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_id')),
                ('loved_by_user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='loved_by_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('post_id', models.CharField(blank=True, default='', max_length=30, null=True, unique=True, verbose_name='post_id')),
                ('post', models.FileField(blank=True, null=True, upload_to='posts/', verbose_name='post')),
                ('post_title', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_title')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='post_image')),
                ('post_played_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='post_played_times')),
                ('post_loved_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='post_loved_number')),
                ('post_comment_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='post_comment_number')),
                ('post_saved_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='post_saved_number')),
                ('post_detail', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='post_detail')),
                ('post_tags', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='post_tags')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('post_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_id')),
                ('comment_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='comment_id')),
                ('comment_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='comment_content')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Loved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('post_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_id')),
                ('loved_by_user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='loved_by_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=25, null=True, unique=True, verbose_name='user_id')),
                ('user_name', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='user_name')),
                ('user_email', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='user_email')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='user_image')),
                ('follower_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='follower_number')),
                ('following_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='following_number')),
                ('listened_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='listened_number')),
            ],
        ),
        migrations.CreateModel(
            name='User_Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('follower_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='follower_id')),
            ],
            options={
                'db_table': 'user_followers',
            },
        ),
        migrations.CreateModel(
            name='User_Followings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('following_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='following_id')),
            ],
            options={
                'db_table': 'user_followings',
            },
        ),
        migrations.CreateModel(
            name='User_Strict_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='user_id')),
                ('user_email', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='user_email')),
                ('user_phone_number', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_phone_number')),
                ('user_birth', models.DateField(blank=True, null=True, verbose_name='user_birth')),
                ('user_password', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_password')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='api.post', to_field='post_id')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='posts',
            field=models.ManyToManyField(through='api.PlaylistPosts', to='api.post'),
        ),
    ]
