# Generated by Django 5.0.4 on 2024-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('post_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_id')),
                ('post_title', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_title')),
                ('post_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='post_content')),
            ],
        ),
    ]
