# Generated by Django 5.0.4 on 2024-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('notification_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='notification_id')),
                ('notification_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='notification_content')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('playlist_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_id')),
                ('playlist_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_name')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('post_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_id')),
                ('comment_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='comment_id')),
                ('comment_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='comment_content')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_id')),
                ('post_detail_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_detail_id')),
                ('post_detail_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='post_detail_content')),
            ],
        ),
        migrations.CreateModel(
            name='User_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('recent', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_experience_id')),
                ('liked', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_experience_title')),
            ],
        ),
        migrations.CreateModel(
            name='User_Strict_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('user_email', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='user_email')),
                ('user_real_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_real_name')),
                ('user_phone_number', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_phone_number')),
                ('user_age', models.IntegerField(blank=True, default=0, null=True, verbose_name='user_age')),
                ('user_password', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_password')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='post_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_loved_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='post_loved_number'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_played_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='post_played_times'),
        ),
    ]
