# Generated by Django 5.0.4 on 2024-05-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_images/', verbose_name='playlist_image'),
        ),
    ]
