# Generated by Django 5.0.4 on 2024-05-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playlist_playlist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('playlist_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_id')),
                ('comment_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='comment_id')),
                ('comment_content', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='comment_content')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Loved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('playlist_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_id')),
                ('loved_by_user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='loved_by_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Loved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('post_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='post_id')),
                ('loved_by_user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='loved_by_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='User_Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('follower_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='follower_id')),
            ],
            options={
                'db_table': 'user_followers',
            },
        ),
        migrations.CreateModel(
            name='User_Followings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='user_id')),
                ('following_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='following_id')),
            ],
            options={
                'db_table': 'user_followings',
            },
        ),
        migrations.DeleteModel(
            name='Post_Detail',
        ),
        migrations.DeleteModel(
            name='User_Experience',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_name',
            new_name='playlist_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_content',
        ),
        migrations.RemoveField(
            model_name='user_strict_information',
            name='user_real_name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_attributes',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='playlist_attributes'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_comment_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_comment_number'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_detail',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='playlist_detail'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_loved_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_loved_number'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_played_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_played_times'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_saved_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='playlist_saved_number'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_comment_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='post_comment_number'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_detail',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='post_detail'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_saved_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='post_saved_number'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='post_tags'),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='follower_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='following_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='listened_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='listened_number'),
        ),
    ]
