# Generated by Django 5.0.4 on 2024-05-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_strict_information',
            name='user_age',
        ),
        migrations.AddField(
            model_name='user_strict_information',
            name='user_birth',
            field=models.DateField(blank=True, null=True, verbose_name='user_birth'),
        ),
    ]
