# Generated by Django 5.0.4 on 2024-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_strict_information_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='user_name'),
        ),
        migrations.AlterField(
            model_name='user_strict_information',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='user_id'),
        ),
    ]
