# Generated by Django 5.0.4 on 2024-06-15 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_playlistposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='posts',
            field=models.ManyToManyField(through='api.PlaylistPosts', to='api.post'),
        ),
        migrations.AlterField(
            model_name='playlistposts',
            name='post',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='api.post', to_field='post_id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True, unique=True, verbose_name='post_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=25, null=True, unique=True, verbose_name='user_id'),
        ),
    ]
