# Generated by Django 5.0.4 on 2024-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_playlistposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='posts',
            field=models.ManyToManyField(through='api.PlaylistPosts', to='api.post'),
        ),
    ]
