# Generated by Django 5.0.4 on 2024-06-15 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_playlistposts_post_alter_post_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True, unique=True, verbose_name='playlist_id'),
        ),
        migrations.AlterField(
            model_name='playlistposts',
            name='playlist',
            field=models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, to='api.playlist', to_field='playlist_id'),
        ),
    ]
