# Generated by Django 5.0.4 on 2024-06-15 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_playlist_playlist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='playlist_id'),
        ),
        migrations.AlterField(
            model_name='playlistposts',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist'),
        ),
    ]
